<?php

namespace Database\Seeders;

use App\Enums\AccessPermission\Permission1FlagEnum;
use App\Enums\AccessPermission\Permission2FlagEnum;
use App\Enums\AccessPermission\Permission3FlagEnum;
use App\Enums\AccessPermission\Permission4FlagEnum;
use App\Enums\Common\UseFlagEnum;
use App\Enums\ScreenName\ContentClassificationEnum;
use App\Enums\ScreenName\DisplayClassificationEnum;
use App\Enums\System\SystemCodeEnum;
use App\Models\AccessPermission;
use App\Models\Display;
use App\Models\Employee;
use App\Models\Login;
use App\Models\System;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ScreenContent90000Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $login = Login::where('login_id', env('DEPLOY_LOGIN_ID'))->first();
        $contractSystem = System::updateOrCreate([
            'code' => SystemCodeEnum::CONTRACT,
        ], [
            'name' => '契約管理システム',
            'start_date' => Carbon::now(),
            'default_permission_2' => Permission2FlagEnum::DATA_VIEWING,
            'default_permission_3' => Permission3FlagEnum::GENERAL_INFORMATION,
            'default_permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION,
            'use_classification' => UseFlagEnum::USE,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id
        ]);

        $employees = Employee::query()->has('logins')->get();
        $existedAccessPermissions = AccessPermission::query()->where('system_id', $contractSystem->id);
        if (!$existedAccessPermissions->count()) {
            $employees->each(function (Employee $employee) use ($contractSystem) {
                AccessPermission::create([
                    'employee_id' => $employee->id,
                    'system_id' => $contractSystem->id,
                    'permission_1' => Permission1FlagEnum::UN_AUTHORIZED_USER,
                    'permission_2' => $contractSystem->default_permission_2,
                    'permission_3' => $contractSystem->default_permission_3,
                    'permission_4' => $contractSystem->default_permission_4,
                    'start_date' => $contractSystem->start_date,
                ]);
            });
        }

        Display::upsert([
            ['system_id' => $contractSystem->id, 'code' => '90000', 'name' => 'ダッシュボード', 'display_classification' => DisplayClassificationEnum::DASHBOARD, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '90100', 'name' => '利用者設定', 'display_classification' => DisplayClassificationEnum::OTHER, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '91000', 'name' => '基本契約一覧', 'display_classification' => DisplayClassificationEnum::LIST, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '91010', 'name' => '基本契約表示', 'display_classification' => DisplayClassificationEnum::DISPLAY, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '91020', 'name' => '基本契約追加', 'display_classification' => DisplayClassificationEnum::ADD, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '91030', 'name' => '基本契約修正', 'display_classification' => DisplayClassificationEnum::EDIT, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '91040', 'name' => '契約条件一覧', 'display_classification' => DisplayClassificationEnum::LIST, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '91050', 'name' => '契約一括登録', 'display_classification' => DisplayClassificationEnum::OTHER, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '91051', 'name' => '契約一括登録確認', 'display_classification' => DisplayClassificationEnum::LIST, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '92010', 'name' => '個別契約表示', 'display_classification' => DisplayClassificationEnum::DISPLAY, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '92020', 'name' => '個別契約追加', 'display_classification' => DisplayClassificationEnum::ADD, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $contractSystem->id, 'code' => '92030', 'name' => '個別契約修正', 'display_classification' => DisplayClassificationEnum::EDIT, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ], ['code']);

        $screen = Display::where('code', '90000')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '15', 'name' => '利用者', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '設定', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => 'トピックス', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '32', 'name' => '利用者権限設定', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '33', 'name' => '利用者権限設定', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '34', 'name' => 'お知らせ管理', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '35', 'name' => 'お知らせ管理', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '51', 'name' => '基本契約', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '52', 'name' => '一覧', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '53', 'name' => '契約状況', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '54', 'name' => '表示', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '55', 'name' => '表示', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '90100')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '設定', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '91000')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '12', 'name' => '一括登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '追加', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '検索', 'classification' => ContentClassificationEnum::SEARCH_FIELD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '一覧', 'classification' => ContentClassificationEnum::LIST, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '32', 'name' => '表示', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '91010')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '12', 'name' => '契約状況', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '16', 'name' => '削除', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '修正', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '承認状況', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '41', 'name' => '個別契約一覧', 'classification' => ContentClassificationEnum::LIST, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '42', 'name' => '追加', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '43', 'name' => '表示', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '51', 'name' => '契約職場', 'classification' => ContentClassificationEnum::LIST, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '52', 'name' => '追加', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '53', 'name' => '表示', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '54', 'name' => '削除', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '61', 'name' => 'ファイル', 'classification' => ContentClassificationEnum::FILE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '62', 'name' => 'ファイル （追加、ペスト、削除）', 'classification' => ContentClassificationEnum::FILE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],

        ]);

        $screen = Display::where('code', '91020')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '91030')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '91040')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '12', 'name' => 'PDF出力', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '契約条件一覧', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '32', 'name' => '追加', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '33', 'name' => '修正', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '34', 'name' => '削除', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '91050')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '契約ダウンロ1ド', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '22', 'name' => 'ダウンロ1ド', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '契約アップロ1ド', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '32', 'name' => 'アップロ1ド', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);
        $screen = Display::where('code', '91051')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => 'メッセ1ジ', 'classification' => ContentClassificationEnum::TOPIC, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '一覧', 'classification' => ContentClassificationEnum::LIST, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '92010')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '16', 'name' => '削除', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '修正', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '個別契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '41', 'name' => 'ファイル', 'classification' => ContentClassificationEnum::FILE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '42', 'name' => 'ファイル （追加、ペスト、削除）', 'classification' => ContentClassificationEnum::FILE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '92020')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '個別契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '92030')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::MASTER_EDIT, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '個別契約情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

    }
}
