<?php

namespace Database\Seeders;

use App\Enums\AccessPermission\Permission1FlagEnum;
use App\Enums\AccessPermission\Permission2FlagEnum;
use App\Enums\AccessPermission\Permission3FlagEnum;
use App\Enums\AccessPermission\Permission4FlagEnum;
use App\Enums\Common\UseFlagEnum;
use App\Enums\ScreenName\ContentClassificationEnum;
use App\Enums\ScreenName\DisplayClassificationEnum;
use App\Enums\System\SystemCodeEnum;
use App\Models\AccessPermission;
use App\Models\Display;
use App\Models\Employee;
use App\Models\Login;
use App\Models\System;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ScreenContent80000Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $login = Login::where('login_id', env('DEPLOY_LOGIN_ID'))->first();
        $facilitySystem = System::updateOrCreate([
            'code' => SystemCodeEnum::FACILITY,
        ], [
            'name' => '設備予約システム',
            'start_date' => Carbon::now(),
            'default_permission_2' => Permission2FlagEnum::DATA_VIEWING,
            'default_permission_3' => Permission3FlagEnum::GENERAL_INFORMATION,
            'default_permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION,
            'use_classification' => UseFlagEnum::USE,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id
        ]);

        $employees = Employee::query()->has('logins')->get();
        $existedAccessPermissions = AccessPermission::query()->where('system_id', $facilitySystem->id);
        if (!$existedAccessPermissions->count()) {
            $employees->each(function (Employee $employee) use ($facilitySystem) {
                AccessPermission::create([
                    'employee_id' => $employee->id,
                    'system_id' => $facilitySystem->id,
                    'permission_1' => Permission1FlagEnum::UN_AUTHORIZED_USER,
                    'permission_2' => $facilitySystem->default_permission_2,
                    'permission_3' => $facilitySystem->default_permission_3,
                    'permission_4' => $facilitySystem->default_permission_4,
                    'start_date' => $facilitySystem->start_date,
                ]);
            });
        }

        Display::upsert([
            ['system_id' => $facilitySystem->id, 'code' => '80000', 'name' => '月間設備予約', 'display_classification' => DisplayClassificationEnum::DASHBOARD, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $facilitySystem->id, 'code' => '80100', 'name' => '利用者設定', 'display_classification' => DisplayClassificationEnum::OTHER, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $facilitySystem->id, 'code' => '81000', 'name' => '設備グループ一覧', 'display_classification' => DisplayClassificationEnum::LIST, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $facilitySystem->id, 'code' => '81010', 'name' => '設備グループ表示', 'display_classification' => DisplayClassificationEnum::DISPLAY, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $facilitySystem->id, 'code' => '81020', 'name' => '設備グループ追加', 'display_classification' => DisplayClassificationEnum::ADD, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $facilitySystem->id, 'code' => '81030', 'name' => '設備グループ修正', 'display_classification' => DisplayClassificationEnum::EDIT, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $facilitySystem->id, 'code' => '82010', 'name' => '設備表示', 'display_classification' => DisplayClassificationEnum::DISPLAY, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $facilitySystem->id, 'code' => '82020', 'name' => '設備追加', 'display_classification' => DisplayClassificationEnum::ADD, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['system_id' => $facilitySystem->id, 'code' => '82030', 'name' => '設備修正', 'display_classification' => DisplayClassificationEnum::EDIT, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ], ['code']);

        $screen = Display::where('code', '80000')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '15', 'name' => '利用者', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '16', 'name' => '設備グループ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '設定', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => 'カレンダー', 'classification' => ContentClassificationEnum::TOPIC, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '22', 'name' => '設備グループ', 'classification' => ContentClassificationEnum::TOPIC, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => 'トピックス', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '32', 'name' => '利用者権限設定', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '33', 'name' => '利用者権限設定', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '34', 'name' => 'お知らせ管理', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '35', 'name' => 'お知らせ登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '80100')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '設定', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_USER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '81000')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '追加', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '検索', 'classification' => ContentClassificationEnum::SEARCH_FIELD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '設備グループ一覧', 'classification' => ContentClassificationEnum::LIST, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '32', 'name' => '表示', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '81010')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '16', 'name' => '削除', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '修正', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => '設備一覧', 'classification' => ContentClassificationEnum::LIST, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '32', 'name' => '追加', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '33', 'name' => '表示', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '81020')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '81030')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '82010')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '16', 'name' => '削除', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '修正', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '31', 'name' => 'ファイル', 'classification' => ContentClassificationEnum::FILE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '32', 'name' => 'ファイル （追加、ペスト、削除）', 'classification' => ContentClassificationEnum::FILE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '82020')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

        $screen = Display::where('code', '82030')->first();
        $screen?->contents()->delete();
        $screen?->contents()->createMany([
            ['no' => '11', 'name' => 'システム名', 'classification' => ContentClassificationEnum::TITLE, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '14', 'name' => 'ヘルプ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '10', 'name' => 'Chat問合せ', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '17', 'name' => '登録', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '18', 'name' => '戻る', 'classification' => ContentClassificationEnum::BUTTON, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
            ['no' => '21', 'name' => '基本情報', 'classification' => ContentClassificationEnum::CARD, 'permission_1' => Permission1FlagEnum::SYSTEM_MANAGER, 'permission_2' => Permission2FlagEnum::DATA_VIEWING, 'permission_3' => Permission3FlagEnum::GENERAL_INFORMATION, 'permission_4' => Permission4FlagEnum::AFFILIATED_DIVISION, 'use_classification' => UseFlagEnum::USE, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'created_by' => $login?->employee_id, 'updated_by' => $login?->employee_id],
        ]);

    }
}
